language: node_js
node_js:
  - "8"
dist: trusty

sudo: false

branches: 
  only: 
  - main
 
cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - cd backend
  - npm run test 
 
